### ISSUE TITLE
label diagramma capitolo 2.5

### ISSUE THREAD

**Issue by madbob** [AgID/lg-acquisizione-e-riuso-software-per-pa-docs#4]
Nel diagramma che descrive la [Macro Fase 2](https://lg-acquisizione-e-riuso-software-per-la-pa.readthedocs.io/it/latest/acquisizione-software/macro-fase-2-analisi-delle-soluzioni-a-riuso-delle-pa-e-delle-soluzioni-open-source.html), la Fase 2.5 dovrebbe essere "Valutazione soluzioni open source". La "Valutazione soluzioni riusabili per la PA" è già la Fase 2.2

**Comment by umbros** [comment]
Grazie @madbob - errore risolto con il commit  [a3c37bb](https://github.com/AgID/lg-acquisizione-e-riuso-software-per-pa-docs/commit/a3c37bbf96740345505ce5b1bc5f163aa231a29e).

Umberto Rosini
Agenzia per l'Italia Digitale
